# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: dov-deploy
#   namespace: dovns
#   labels:
#     app: dov
#     name: dov-deploy
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: myapp
#       dept: eng
#       commit: abc123
#   template:
#     metadata:
#       name: mypod
#       namespace: dovns
#       labels:
#         app: myapp
#         dept: eng
#         commit: abc123
#     spec:
#       containers:
#       - name: mypod-dancing-bear
#         image: chukmunnlee/dov-bear:v5
#         imagePullPolicy: IfNotPresent
#         ports:
#         - name: app-port
#           containerPort: 3000
#         resources:
#           requests:
#             cpu: 100m
#             memory: 256Mi
#           limits:
#             cpu: 100m
#             memory: 256Mi
#         env:
#         - name: INSTANCE_NAME
#           valueFrom:
#             fieldRef:
#               fieldPath: metadata.name
#         - name: INSTANCE_HASH
#           valueFrom:
#             fieldRef:
#               fieldPath: metadata.labels['pod-template-hash']

---
apiVersion: v1
kind: Service
metadata: 
  name: dov-svc
  namespace: dov-ns
  labels:
    app: dov
    name: dov-svc
spec:
  type: ClusterIP
  selector: 
    app: dov
    dept: eng
    commit: abc123
  ports: 
  - port: 8080
    targetPort: app-port

---
apiVersion: v1
kind: Service
metadata: 
  name: dov-hsvc
  namespace: dov-ns
  labels:
    app: dov
    name: dov-hsvc
spec:
  clusterIP: None
  selector: 
    app: dov
  ports: 
  - port: 8080
    targetPort: app-port

---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: dov-sts
  namespace: dov-ns
spec:
  replicas: 3
  serviceName: dov-hsvc
  selector:
    matchLabels:
      app: dov
  template:
    metadata:
      name: dov-po
      namespace: dov-ns
      labels:
        app: dov
    spec:
      containers:
      - name: dov-container
        image: chukmunnlee/dov-bear:v5
        imagePullPolicy: IfNotPresent
        ports:
        - name: app-port
          containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pod-template-hash']
              