---
apiVersion: v1
kind: Service
metadata:
  name: mysql-hsvc
  namespace: mysql-ns
  labels:
    app: mysql
    name: mysql-hsvc
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-sts
  namespace: mysql-ns
spec:
  replicas: 2
  serviceName: mysql-hsvc
  selector:
    matchLabels:
      app: mysql
  volumeClaimTemplates:
  - metadata:
      name: data-vol
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: do-block-storage
      # volumeName: pvc-abc123  # Specify the existing PV here if was created by admin
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:8
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeit
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data-vol
          mountPath: /var/lib/mysql

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-write-svc
  namespace: mysql-ns
spec:
  type: ClusterIP
  selector:
    app: mysql
    apps.kubernetes.io/pod-index: "0"
  ports:
  - port: 3306
    targetPort: 3306