---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  namespace: dov-ns
  labels:
    app: dov
    name: dov-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dov
  template:
    metadata:
      name: dov-po
      namespace: dov-ns
      labels:
        app: dov
    spec:
      containers:
      - name: dov-container
        image: chukmunnlee/dov-bear:v5
        imagePullPolicy: IfNotPresent
        ports:
        - name: app-port
          containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pod-template-hash']

---
apiVersion: v1
kind: Service
metadata: 
  name: dov-svc
  namespace: dov-ns
  labels:
    app: dov
    name: dov-svc
spec:
  type: ClusterIP
  selector: 
    app: dov
  ports: 
  - port: 8000
    targetPort: app-port
