---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  namespace: dovns
  labels:
    app: dov
    name: dov-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      dept: eng
      commit: abc123
  template:
    metadata:
      name: mypod
      namespace: dovns
      labels:
        app: myapp
        dept: eng
        commit: abc123
    spec:
      containers:
      - name: mypod-dancing-bear
        image: chukmunnlee/dov-bear:v5
        imagePullPolicy: IfNotPresent
        ports:
        - name: app-port
          containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 256Mi
        env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pod-template-hash']

---
apiVersion: v1
kind: Service
metadata: 
  name: dov-svc
  namespace: dovns
  labels:
    app: dov
    name: dov-svc
spec:
  type: ClusterIP
  selector: 
    app: myapp
    dept: eng
    commit: abc123
  ports: 
  - port: 8000
    targetPort: app-port
