apiVersion: v1
items:
- apiVersion: v1
  data:
    INSTANCE_NAME: prod-version
    config.cnf: |
      hello world
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"INSTANCE_NAME":"prod-version","config.cnf":"hello world\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"env":"prod"},"name":"prod-dov-cm-hhb26db82h","namespace":"prod-dovns"}}
    labels:
      env: prod
    name: prod-dov-cm-hhb26db82h
    namespace: prod-dovns
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"dov","env":"prod","name":"dov-svc"},"name":"prod-dov-svc","namespace":"prod-dovns"},"spec":{"ports":[{"port":8000,"targetPort":"app-port"}],"selector":{"app":"myapp","commit":"abc123","dept":"eng","env":"prod"},"type":"ClusterIP"}}
    labels:
      app: dov
      env: prod
      name: dov-svc
    name: prod-dov-svc
    namespace: prod-dovns
  spec:
    ports:
    - port: 8000
      targetPort: app-port
    selector:
      app: myapp
      commit: abc123
      dept: eng
      env: prod
    type: ClusterIP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"dov","env":"prod","name":"dov-deploy"},"name":"prod-dov-deploy","namespace":"prod-dovns"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"myapp","commit":"abc123","dept":"eng","env":"prod"}},"template":{"metadata":{"labels":{"app":"myapp","commit":"abc123","dept":"eng","env":"prod"},"name":"mypod","namespace":"dovns"},"spec":{"containers":[{"env":[{"name":"INSTANCE_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"INSTANCE_HASH","valueFrom":{"fieldRef":{"fieldPath":"metadata.labels['pod-template-hash']"}}}],"image":"chukmunnlee/dov-bear:v5prod","imagePullPolicy":"IfNotPresent","name":"mypod-dancing-bear","ports":[{"containerPort":3000,"name":"app-port"}],"resources":{"limits":{"cpu":"100m","memory":"256Mi"},"requests":{"cpu":"200m","memory":"512Mi"}}}]}}}}
    labels:
      app: dov
      env: prod
      name: dov-deploy
    name: prod-dov-deploy
    namespace: prod-dovns
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: myapp
        commit: abc123
        dept: eng
        env: prod
    template:
      metadata:
        labels:
          app: myapp
          commit: abc123
          dept: eng
          env: prod
        name: mypod
        namespace: dovns
      spec:
        containers:
        - env:
          - name: INSTANCE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: INSTANCE_HASH
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['pod-template-hash']
          image: chukmunnlee/dov-bear:v5prod
          imagePullPolicy: IfNotPresent
          name: mypod-dancing-bear
          ports:
          - containerPort: 3000
            name: app-port
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 512Mi
kind: List
metadata: {}
